sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yizhong106518
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: PeZIJBmCLv6OCYrLy45R78tMptWSqC
    access-key-id: LTAI5t8bLdR5KXAtVuJNPodx
    bucket-name: skytakeout-study
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxe306069b374c278c
    secret: 5776f23274261fd7d0926727f209ab7c
server:
  port: 8110

